In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Crear un arrya desde numpy

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,15,100)

array([ 0.        ,  0.15151515,  0.3030303 ,  0.45454545,  0.60606061,
        0.75757576,  0.90909091,  1.06060606,  1.21212121,  1.36363636,
        1.51515152,  1.66666667,  1.81818182,  1.96969697,  2.12121212,
        2.27272727,  2.42424242,  2.57575758,  2.72727273,  2.87878788,
        3.03030303,  3.18181818,  3.33333333,  3.48484848,  3.63636364,
        3.78787879,  3.93939394,  4.09090909,  4.24242424,  4.39393939,
        4.54545455,  4.6969697 ,  4.84848485,  5.        ,  5.15151515,
        5.3030303 ,  5.45454545,  5.60606061,  5.75757576,  5.90909091,
        6.06060606,  6.21212121,  6.36363636,  6.51515152,  6.66666667,
        6.81818182,  6.96969697,  7.12121212,  7.27272727,  7.42424242,
        7.57575758,  7.72727273,  7.87878788,  8.03030303,  8.18181818,
        8.33333333,  8.48484848,  8.63636364,  8.78787879,  8.93939394,
        9.09090909,  9.24242424,  9.39393939,  9.54545455,  9.6969697 ,
        9.84848485, 10.        , 10.15151515, 10.3030303 , 10.45

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand()

0.7509567686343482

In [19]:
np.random.rand(4,4)

array([[0.95216022, 0.0355999 , 0.39632671, 0.72195364],
       [0.09869404, 0.2858737 , 0.41855067, 0.91697354],
       [0.71401352, 0.56423543, 0.87997503, 0.81609013],
       [0.23263791, 0.88480233, 0.47227183, 0.12494115]])

In [20]:
np.random.randint(1,15)

10

In [21]:
np.random.randint(1,100,(10,10))

array([[42, 29, 86, 34, 17, 20, 55, 70, 81, 96],
       [30, 67, 72, 53, 55, 38, 77, 35, 53, 10],
       [30, 57, 15, 73, 99, 82, 24, 46, 30, 79],
       [69, 22, 22, 91, 12, 94, 80, 34,  3, 75],
       [73, 22, 25, 54, 55, 64, 85, 77, 64, 24],
       [29, 10, 86, 66, 11, 12, 75, 67, 87, 28],
       [94, 91,  2, 10, 28, 78, 91, 96, 58, 82],
       [49, 54, 60, 57, 37, 32, 24, 82, 90, 24],
       [70, 59, 24, 47, 94, 19, 26, 21, 75, 13],
       [ 8, 95, 66, 99, 91,  8, 90, 51,  8, 38]])