In [2]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
arr = np.array(lista)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr[0]

1

In [16]:
arr[0] + arr[5]

7

In [17]:
matriz[0]

array([1, 2, 3])

In [19]:
matriz[0,2]

3

In [22]:
arr[0:3]

array([1, 2, 3])

In [25]:
arr[::3]

array([1, 4, 7])

In [27]:
arr[-3:]

array([7, 8, 9])

In [28]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])