In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
arr

array([ 9,  8, 12, 19, 19, 18, 17,  1, 13, 18])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[ 9,  8, 12, 19, 19],
       [18, 17,  1, 13, 18]])

## Max
- Obtiene el numero más grande
- En caso de una matriz se puede buscar por filas(1) y columnas(0)

In [9]:
matriz.max(0)

array([18, 17, 12, 19, 19])

## argmax
- Muestra el indice del mayor valor
- En caso de una matriz se puede buscar por filas(1) y columnas(0)

In [11]:
arr.argmax()

3

In [12]:
matriz.argmax(0)

array([1, 1, 0, 0, 0])

## Min
- Obtiene el numero de menor valor
- En caso de una matriz se puede buscar por filas(1) y columnas(0)

In [13]:
arr.min()

1

In [15]:
matriz.min(1)

array([8, 1])

## argmin
- Muestra el indice del menor valor
- En caso de una matriz se puede buscar por filas(1) y columnas(0)

In [16]:
arr.argmin()

7

In [19]:
matriz.argmin(1)

array([1, 2])

## pick to pick
- Muestra la diferencia del pico menor al pico mayor
- En caso de una matriz se puede buscar por filas(1) y columnas(0)

In [21]:
arr

array([ 9,  8, 12, 19, 19, 18, 17,  1, 13, 18])

In [22]:
arr.ptp()

18

In [23]:
matriz

array([[ 9,  8, 12, 19, 19],
       [18, 17,  1, 13, 18]])

In [25]:
matriz.ptp(0)

array([ 9,  9, 11,  6,  1])

## Percentil
### Nota tiene que estar ordenado el array
1. i = nk el porcentage del percentil * la cantidad de datos  
2. Si el numero no es entero se toma el siguiente número
3. .50 x 10 = 5
4. si el numero es entero
5. pk = i + (i+1)/2
6. 5 +(5+1)/2 = 5.5
7. Se toma la posicion entre 5.5 de la lista y se promedia
8. 19+18/2 = 


In [29]:
arr

array([ 9,  8, 12, 19, 19, 18, 17,  1, 13, 18])

In [30]:
np.percentile(arr,50)

15.0

## Sort
- ordena los numero del array

In [31]:
arr.sort()
arr

array([ 1,  8,  9, 12, 13, 17, 18, 18, 19, 19])

## median
- obtiene la mediana

In [32]:
np.median(arr)

15.0

In [34]:
np.median(matriz,1)

array([ 9., 18.])

## std
- Obtiene la desviación estandar

In [35]:
np.std(arr)

5.678027826631356

## var
- obtiene la variansa
- La desviacion estandar elevada al cuadrado obitene la variansa

In [36]:
np.var(arr)

32.24

In [37]:
np.std(arr) **2

32.24

## mean
- obtiene la media

In [38]:
np.mean(arr)

13.4

## concatenate
- Unir dos lista

In [46]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b = np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [49]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [48]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])