In [3]:
import numpy as np

In [7]:
arr = np.random.randint(1,10,(3,2))
arr

array([[1, 2],
       [7, 4],
       [4, 8]])

### Shape
- Cuantas columnas y filas  tiene un arreglo

In [8]:
arr.shape

(3, 2)

### Reshape
- Cambia la forma establecida en un array

In [9]:
arr.reshape(1,6)

array([[1, 2, 7, 4, 4, 8]])

In [13]:
arr.reshape(2,3)

array([[1, 2, 7],
       [4, 4, 8]])

In [14]:
np.reshape(arr,(1,6))

array([[1, 2, 7, 4, 4, 8]])

In [15]:
arr

array([[1, 2],
       [7, 4],
       [4, 8]])

In [16]:
np.reshape(arr,(2,3),'C')

array([[1, 2, 7],
       [4, 4, 8]])

In [17]:
np.reshape(arr,(2,3),'F')

array([[1, 4, 4],
       [7, 2, 8]])

In [18]:
np.reshape(arr,(2,3),'A')

array([[1, 2, 7],
       [4, 4, 8]])